import { create } from 'storybook/theming/create';

/** Дизайн-токены ИС «Отчёты» (согласованы с src/scss и страницами приложения) */
export const etuBrand = {
  navy: '#05336e',
  blue: '#2563eb',
  sidebarBlue: '#1e3a8a',
  gold: '#bb8d54',
  bgApp: '#f4f6f9',
  bgPage: '#f5f6f8',
  surface: '#ffffff',
  border: '#e5e7eb',
  borderStrong: '#d1d5db',
  text: '#111827',
  textSecondary: '#6b7280',
  textMuted: '#9ca3af',
  success: '#166534',
  successBg: '#dcfce7',
  radius: 10,
  radiusLg: 12,
  font: '"Inter", "Segoe UI", system-ui, -apple-system, sans-serif',
  fontMono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
} as const;

/** Светлая тема UI Storybook — как в рабочем интерфейсе ИС «Отчёты» */
export const etuTheme = create({
  base: 'light',
  brandTitle: 'ИС «Отчёты» · UI-kit',
  brandUrl: '/',
  brandImage: '/logo-leti.png',
  brandTarget: '_self',
  colorPrimary: etuBrand.navy,
  colorSecondary: etuBrand.blue,
  appBg: etuBrand.surface,
  appContentBg: etuBrand.surface,
  appHoverBg: '#eff6ff',
  appPreviewBg: etuBrand.bgApp,
  appBorderColor: etuBrand.border,
  appBorderRadius: etuBrand.radius,
  fontBase: etuBrand.font,
  fontCode: etuBrand.fontMono,
  textColor: etuBrand.text,
  textInverseColor: etuBrand.surface,
  textMutedColor: etuBrand.textMuted,
  barTextColor: etuBrand.textSecondary,
  barHoverColor: etuBrand.blue,
  barSelectedColor: etuBrand.blue,
  barBg: etuBrand.surface,
  buttonBg: etuBrand.bgApp,
  buttonBorder: etuBrand.border,
  booleanBg: etuBrand.bgApp,
  booleanSelectedBg: '#eff6ff',
  inputBg: etuBrand.surface,
  inputBorder: etuBrand.borderStrong,
  inputTextColor: etuBrand.text,
  inputBorderRadius: 8,
});
